bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Zellij, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "zellij"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser --new-window
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, S, Music (spotify), exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, P, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT, M, Displays (hyprmon), exec, omarchy-launch-tui hyprmon

# WebApp-ish replacements using Firefox
bindd = SUPER SHIFT, A, Copilot, exec, omarchy-launch-browser --new-window "https://copilot.microsoft.com"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Prev workspace
unbind = SUPER CTRL, TAB
bindd = SUPER, GRAVE, Former workspace, workspace, previous

# Default to dwindle workspace
unbind = SUPER, L

# Unbind old bindings for vim motions
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, LEFT
unbind = SUPER, DOWN
unbind = SUPER, UP
unbind = SUPER, RIGHT
unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, DOWN
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, RIGHT

# Vim motions for window focus and swap
# Focus
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r
# Swap
bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, J, swapwindow, d
bind = SUPER SHIFT, K, swapwindow, u
bind = SUPER SHIFT, L, swapwindow, r

# Toggle splitting mode
bind = SUPER, BACKSLASH, layoutmsg, togglesplit

# Walker keymaps on forward slash (code:53)
bind = SUPER, X, exec, omarchy-menu-keybindings

# Workspace navigation (GNOME-style)
unbind = SUPER CTRL, LEFT
unbind = SUPER CTRL, RIGHT
unbind = SUPER, TAB
unbind = SUPER SHIFT, TAB
bindd = SUPER CTRL, LEFT, Previous workspace, workspace, e-1
bindd = SUPER CTRL, RIGHT, Next workspace, workspace, e+1

# Rebind grouped window focus to CTRL ALT
bind = SUPER CTRL ALT, LEFT, changegroupactive, b
bind = SUPER CTRL ALT, RIGHT, changegroupactive, f

# Custom window switcher until elephant-windows support
bind = SUPER, Tab, exec, ghostty --title="h-switcher" -e ~/.config/hypr/scripts/h-switcher.sh
